meta_product_name: "Your Urban Potager"
meta_title: "Your Urban Potager - Easily grow your vegetables in your apartment."
meta_description: "Your Urban Potager assits you in the preparation and planning of your own veggies."
meta_image: "cover.png" # should exist in `app/assets/images/`
